# Generated by Django 2.2.12 on 2020-05-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoQuack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_time', models.DateField()),
                ('tag', models.CharField(max_length=100)),
                ('cipher_unsolved', models.FileField(upload_to='crypto_quack_unsolved')),
                ('cipher_solved', models.FileField(upload_to='crypto_quack_solved')),
            ],
        ),
        migrations.CreateModel(
            name='QuackForum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=300)),
                ('user', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
