# Generated by Django 2.2.12 on 2020-05-14 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quack_forum', '0002_cryptoquack_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptoquack',
            options={'verbose_name': 'šifra', 'verbose_name_plural': 'Šifry'},
        ),
        migrations.AlterModelOptions(
            name='quackforum',
            options={'verbose_name': 'kvák', 'verbose_name_plural': 'Kváky'},
        ),
    ]
