# Generated by Django 2.2.12 on 2020-05-15 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quack_forum', '0003_auto_20200514_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptoquack',
            name='publish_time',
        ),
    ]
