# Generated by Django 2.2.12 on 2020-05-14 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'tým', 'verbose_name_plural': 'Týmy'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'soupiska', 'verbose_name_plural': 'Soupisky'},
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(blank=True, max_length=50)),
                ('variable_symbol', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'platební údaj',
                'verbose_name_plural': 'Platební údaje',
            },
        ),
    ]
