# Generated by Django 2.2.12 on 2020-05-13 22:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='displaymodel',
            name='is_active',
        ),
        migrations.AddField(
            model_name='displaymodel',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='displaymodel',
            name='title',
            field=models.CharField(default=datetime.date(2020, 5, 14), max_length=100),
            preserve_default=False,
        ),
    ]
