# Generated by Django 2.2.12 on 2020-05-14 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='displaymodel',
            options={'verbose_name': 'budíček', 'verbose_name_plural': 'Zde se nastavuje přístupnost na stránce'},
        ),
    ]
