# Generated by Django 2.2.12 on 2020-05-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_app', '0002_auto_20200514_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displaymodel',
            name='date',
            field=models.DateField(),
        ),
    ]
